/**
 * Audio Agent — Procedural Music & SFX Generator
 * Implements SRS FR-7, §7.4
 *
 * Generates a self-contained audio.js module using only:
 *   - AudioContext
 *   - OscillatorNode
 *   - GainNode
 *   - BiquadFilterNode
 *   - DelayNode
 *
 * No external audio assets, no network requests.
 * Produces background music, SFX, and ambient sound.
 */

import type { ProjectBlueprint } from '../../director/src/schema.js'
import { AIRouter } from '@vibestudio/shared/src/ai/router.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type MusicStyle = 'chiptune' | 'ambient' | 'orchestral' | 'synthwave'

export interface AudioConfig {
  style:      MusicStyle
  tempo:      number          // BPM
  key:        number          // root frequency in Hz (e.g. 261.63 = C4)
  scale:      number[]        // intervals from root (semitones)
  hasMusic:   boolean
  hasSfx:     boolean
  hasAmbient: boolean
}

export interface AudioAgentOutput {
  config:    AudioConfig
  audioCode: string           // complete audio.js file content
}

// ---------------------------------------------------------------------------
// Scale definitions (semitone intervals from root)
// ---------------------------------------------------------------------------

const SCALES: Record<string, number[]> = {
  minor:      [0, 2, 3, 5, 7, 8, 10],
  major:      [0, 2, 4, 5, 7, 9, 11],
  pentatonic: [0, 3, 5, 7, 10],
  dorian:     [0, 2, 3, 5, 7, 9, 10],
  phrygian:   [0, 1, 3, 5, 7, 8, 10],
}

// ---------------------------------------------------------------------------
// Genre → audio config mapping
// ---------------------------------------------------------------------------

function buildAudioConfig(blueprint: ProjectBlueprint): AudioConfig {
  const genre = blueprint.gameplay.genre.toLowerCase()

  const presets: Partial<Record<string, Partial<AudioConfig>>> = {
    survival:  { style: 'chiptune', tempo: 140, key: 220,   scale: SCALES.minor },
    shooter:   { style: 'chiptune', tempo: 160, key: 261.63, scale: SCALES.phrygian },
    platformer:{ style: 'chiptune', tempo: 120, key: 293.66, scale: SCALES.major },
    puzzle:    { style: 'ambient',  tempo: 70,  key: 246.94, scale: SCALES.dorian },
    rpg:       { style: 'orchestral', tempo: 90, key: 196,   scale: SCALES.minor },
    racing:    { style: 'synthwave', tempo: 175, key: 311.13, scale: SCALES.pentatonic },
    arcade:    { style: 'chiptune', tempo: 150, key: 261.63, scale: SCALES.major },
  }

  const matched = Object.entries(presets).find(([k]) => genre.includes(k))
  const preset  = matched?.[1] ?? presets.arcade!

  return {
    style:      (preset.style    ?? 'chiptune') as MusicStyle,
    tempo:      preset.tempo     ?? 140,
    key:        preset.key       ?? 261.63,
    scale:      preset.scale     ?? SCALES.minor,
    hasMusic:   blueprint.audio.hasBackgroundMusic,
    hasSfx:     blueprint.audio.hasSoundEffects,
    hasAmbient: blueprint.audio.hasAmbientSound,
  }
}

// ---------------------------------------------------------------------------
// Code generator — produces audio.js
// ---------------------------------------------------------------------------

function generateAudioCode(cfg: AudioConfig): string {
  const scaleJSON   = JSON.stringify(cfg.scale)
  const tempo       = cfg.tempo
  const rootHz      = cfg.key
  const style       = cfg.style
  const hasMusic    = cfg.hasMusic
  const hasSfx      = cfg.hasSfx
  const hasAmbient  = cfg.hasAmbient

  return `/**
 * VibeStudio AI — Generated Audio Module
 * Implements SRS FR-7 — Web Audio API procedural audio
 *
 * Style: ${style} | Tempo: ${tempo} BPM | Root: ${rootHz.toFixed(2)} Hz
 * AUTO-GENERATED by Audio Agent — do not edit manually
 */

// ============================================================
// AudioContext singleton
// ============================================================

let _ctx = null

function getCtx() {
  if (!_ctx) _ctx = new (window.AudioContext || window.webkitAudioContext)()
  if (_ctx.state === 'suspended') _ctx.resume()
  return _ctx
}

// ============================================================
// Helpers
// ============================================================

const ROOT_HZ    = ${rootHz}
const SCALE      = ${scaleJSON}
const TEMPO_BPM  = ${tempo}
const BEAT_SEC   = 60 / TEMPO_BPM

/** Semitone to frequency relative to root */
function semitoneHz(semitone) {
  return ROOT_HZ * Math.pow(2, semitone / 12)
}

/** Pick a scale degree (0-based) → Hz */
function scaleNote(degree) {
  const oct    = Math.floor(degree / SCALE.length)
  const idx    = degree % SCALE.length
  return semitoneHz(SCALE[idx] + oct * 12)
}

function createGain(ctx, vol = 0.3) {
  const g = ctx.createGain()
  g.gain.value = vol
  g.connect(ctx.destination)
  return g
}

function playTone(ctx, freq, type = 'square', start = 0, dur = 0.1, vol = 0.15, master) {
  const osc  = ctx.createOscillator()
  const gain = ctx.createGain()
  osc.type = type
  osc.frequency.value = freq
  gain.gain.setValueAtTime(vol, start)
  gain.gain.exponentialRampToValueAtTime(0.0001, start + dur)
  osc.connect(gain)
  gain.connect(master ?? ctx.destination)
  osc.start(start)
  osc.stop(start + dur + 0.01)
}

// ============================================================
// Background Music — ${style} style (FR-7)
// ============================================================

let _musicStop = null

${hasMusic ? generateMusicEngine(style, tempo, rootHz) : `
export function startMusic() { console.log('[Audio] Music disabled') }
export function stopMusic() {}
`}

// ============================================================
// Sound Effects (FR-7)
// ============================================================

${hasSfx ? generateSfxEngine(style) : `
export const sfx = { shoot: ()=>{}, hit: ()=>{}, death: ()=>{}, pickup: ()=>{}, waveStart: ()=>{}, gameOver: ()=>{} }
`}

// ============================================================
// Ambient Sound (FR-7)
// ============================================================

${hasAmbient ? generateAmbientEngine() : `
export function startAmbient() {}
export function stopAmbient() {}
`}

// ============================================================
// Master init
// ============================================================

export function initAudio() {
  // Unlock AudioContext on first user gesture (browser requirement)
  const unlock = () => {
    getCtx()
    document.removeEventListener('pointerdown', unlock)
    document.removeEventListener('keydown', unlock)
  }
  document.addEventListener('pointerdown', unlock)
  document.addEventListener('keydown', unlock)
}
`
}

// ---------------------------------------------------------------------------
// Music engine templates
// ---------------------------------------------------------------------------

function generateMusicEngine(style: MusicStyle, tempo: number, root: number): string {
  const beatSec = (60 / tempo).toFixed(4)

  const melodyPatterns: Record<MusicStyle, string> = {
    chiptune: `
  // Chiptune arpeggio melody — rising scale pattern
  const patterns = [
    [0,2,4,6, 4,2,0,2, 3,5,3,1, 0,2,4,6],
    [0,4,7,4, 0,4,7,9, 7,4,0,4, 7,9,7,4],
  ]`,
    ambient: `
  // Ambient slow chord wash
  const patterns = [
    [0,0,4,4, 2,2,6,6, 3,3,5,5, 1,1,4,4],
    [0,3,5,3, 0,3,5,7, 5,3,0,3, 5,7,5,3],
  ]`,
    orchestral: `
  // Orchestral theme with variation
  const patterns = [
    [0,2,4,5, 4,2,0,4, 3,5,7,5, 4,2,0,2],
    [7,5,4,2, 0,2,4,5, 3,5,4,2, 0,2,3,4],
  ]`,
    synthwave: `
  // Synthwave pulsing bassline + lead
  const patterns = [
    [0,0,7,0, 5,0,7,0, 3,0,5,0, 4,0,5,0],
    [0,4,7,4, 9,7,4,7, 5,9,7,5, 4,7,9,7],
  ]`,
  }

  const waveType: Record<MusicStyle, string> = {
    chiptune: 'square',
    ambient: 'sine',
    orchestral: 'triangle',
    synthwave: 'sawtooth',
  }

  const wave = waveType[style]
  const pat  = melodyPatterns[style]

  return `
let _musicScheduler = null
let _musicMaster    = null
let _patternIdx     = 0
let _noteIdx        = 0

${pat}

const PATTERN_LEN = patterns[0].length
const BEAT = ${beatSec}

export function startMusic() {
  const ctx = getCtx()
  stopMusic()

  _musicMaster = ctx.createGain()

  // Compressor for cleaner mix
  const comp = ctx.createDynamicsCompressor()
  comp.threshold.value = -12
  comp.ratio.value = 4
  _musicMaster.connect(comp)
  comp.connect(ctx.destination)

  ${style === 'chiptune' ? `
  // Low-pass filter for lo-fi chip feel
  const filter = ctx.createBiquadFilter()
  filter.type = 'lowpass'
  filter.frequency.value = 2800
  _musicMaster.connect(filter)
  filter.connect(comp)` : ''}

  ${style === 'synthwave' ? `
  // Chorus/delay for synthwave
  const delay = ctx.createDelay(0.5)
  delay.delayTime.value = 0.08
  const delGain = ctx.createGain()
  delGain.gain.value = 0.3
  _musicMaster.connect(delay)
  delay.connect(delGain)
  delGain.connect(ctx.destination)` : ''}

  function scheduleNote() {
    const now  = ctx.currentTime
    const pat  = patterns[_patternIdx % patterns.length]
    const deg  = pat[_noteIdx % PATTERN_LEN]
    const freq = scaleNote(deg)
    const dur  = BEAT * (deg === 0 ? 1.5 : 1.0)
    const vol  = _noteIdx % 4 === 0 ? 0.18 : 0.12

    playTone(ctx, freq, '${wave}', now, dur, vol, _musicMaster)

    // Bass note every 4 beats
    if (_noteIdx % 4 === 0) {
      playTone(ctx, freq * 0.5, '${wave}', now, BEAT * 2, 0.10, _musicMaster)
    }

    _noteIdx++
    if (_noteIdx >= PATTERN_LEN) { _noteIdx = 0; _patternIdx++ }

    _musicScheduler = setTimeout(scheduleNote, BEAT * 1000 * 0.98)
  }

  scheduleNote()
}

export function stopMusic() {
  if (_musicScheduler) clearTimeout(_musicScheduler)
  if (_musicMaster) { _musicMaster.disconnect(); _musicMaster = null }
  _noteIdx = 0; _patternIdx = 0
}
`
}

// ---------------------------------------------------------------------------
// SFX engine
// ---------------------------------------------------------------------------

function generateSfxEngine(style: MusicStyle): string {
  const baseWave = style === 'chiptune' ? 'square' : style === 'synthwave' ? 'sawtooth' : 'triangle'

  return `
export const sfx = {
  /** Shoot / fire bullet */
  shoot() {
    const ctx = getCtx()
    const osc = ctx.createOscillator()
    const g   = ctx.createGain()
    osc.type = 'square'
    osc.frequency.setValueAtTime(880, ctx.currentTime)
    osc.frequency.exponentialRampToValueAtTime(220, ctx.currentTime + 0.08)
    g.gain.setValueAtTime(0.15, ctx.currentTime)
    g.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.1)
    osc.connect(g); g.connect(ctx.destination)
    osc.start(); osc.stop(ctx.currentTime + 0.12)
  },

  /** Enemy hit */
  hit() {
    const ctx = getCtx()
    const t   = ctx.currentTime
    // Noise burst via white noise buffer
    const buf = ctx.createBuffer(1, ctx.sampleRate * 0.08, ctx.sampleRate)
    const data = buf.getChannelData(0)
    for (let i = 0; i < data.length; i++) data[i] = Math.random() * 2 - 1
    const src = ctx.createBufferSource()
    const flt = ctx.createBiquadFilter()
    const g   = ctx.createGain()
    src.buffer = buf
    flt.type = 'bandpass'; flt.frequency.value = 800; flt.Q.value = 0.5
    g.gain.setValueAtTime(0.3, t)
    g.gain.exponentialRampToValueAtTime(0.001, t + 0.08)
    src.connect(flt); flt.connect(g); g.connect(ctx.destination)
    src.start()
  },

  /** Player/entity death */
  death() {
    const ctx = getCtx()
    const t   = ctx.currentTime
    for (let i = 0; i < 4; i++) {
      playTone(ctx, 440 - i * 80, '${baseWave}', t + i * 0.07, 0.1, 0.12)
    }
    // Noise tail
    const buf = ctx.createBuffer(1, ctx.sampleRate * 0.3, ctx.sampleRate)
    const d   = buf.getChannelData(0)
    for (let j = 0; j < d.length; j++) d[j] = (Math.random() * 2 - 1) * (1 - j / d.length)
    const src = ctx.createBufferSource()
    const g   = ctx.createGain()
    src.buffer = buf; g.gain.value = 0.2
    src.connect(g); g.connect(ctx.destination)
    src.start(t + 0.28)
  },

  /** Coin / item pickup */
  pickup() {
    const ctx = getCtx()
    const t   = ctx.currentTime
    const notes = [523, 659, 784, 1047]
    notes.forEach((hz, i) => playTone(ctx, hz, 'sine', t + i * 0.06, 0.08, 0.15))
  },

  /** Wave start announcement */
  waveStart() {
    const ctx = getCtx()
    const t   = ctx.currentTime
    const notes = [261, 329, 392, 523]
    notes.forEach((hz, i) => playTone(ctx, hz, 'square', t + i * 0.1, 0.15, 0.12))
  },

  /** Game over jingle */
  gameOver() {
    const ctx = getCtx()
    const t   = ctx.currentTime
    const notes = [523, 494, 440, 392, 349, 330, 294, 261]
    notes.forEach((hz, i) => playTone(ctx, hz, '${baseWave}', t + i * 0.12, 0.18, 0.13))
  },

  /** Level complete / win */
  win() {
    const ctx = getCtx()
    const t   = ctx.currentTime
    const notes = [523, 587, 659, 784, 880, 1047]
    notes.forEach((hz, i) => playTone(ctx, hz, 'sine', t + i * 0.09, 0.15, 0.14))
  },

  /** Player invincibility flash */
  shield() {
    const ctx = getCtx()
    const osc = ctx.createOscillator()
    const g   = ctx.createGain()
    osc.type = 'sine'
    osc.frequency.setValueAtTime(1200, ctx.currentTime)
    osc.frequency.exponentialRampToValueAtTime(600, ctx.currentTime + 0.15)
    g.gain.setValueAtTime(0.12, ctx.currentTime)
    g.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.18)
    osc.connect(g); g.connect(ctx.destination)
    osc.start(); osc.stop(ctx.currentTime + 0.2)
  },
}
`
}

// ---------------------------------------------------------------------------
// Ambient engine
// ---------------------------------------------------------------------------

function generateAmbientEngine(): string {
  return `
let _ambientNodes = []

export function startAmbient() {
  const ctx  = getCtx()
  stopAmbient()

  // Deep drone pad
  function makeDrone(freq, vol = 0.04) {
    const osc  = ctx.createOscillator()
    const gain = ctx.createGain()
    const flt  = ctx.createBiquadFilter()
    osc.type = 'sine'
    osc.frequency.value = freq
    flt.type = 'lowpass'; flt.frequency.value = 600
    gain.gain.value = vol
    osc.connect(flt); flt.connect(gain); gain.connect(ctx.destination)
    osc.start()
    _ambientNodes.push(osc, gain)
  }

  makeDrone(55,   0.05)   // sub bass
  makeDrone(110,  0.03)   // bass
  makeDrone(220,  0.02)   // lower mid
  makeDrone(330,  0.015)  // mid

  // Slow LFO modulation on the bass drone
  const lfo  = ctx.createOscillator()
  const lfoG = ctx.createGain()
  lfo.type = 'sine'
  lfo.frequency.value = 0.12   // 0.12 Hz = ~8s cycle
  lfoG.gain.value = 15         // modulate ±15 Hz
  lfo.connect(lfoG)
  // Connect LFO to first drone's frequency
  if (_ambientNodes[0]) lfoG.connect(_ambientNodes[0].frequency)
  lfo.start()
  _ambientNodes.push(lfo, lfoG)
}

export function stopAmbient() {
  _ambientNodes.forEach(n => { try { n.stop?.(); n.disconnect?.() } catch {} })
  _ambientNodes = []
}
`
}

// ---------------------------------------------------------------------------
// Main entry
// ---------------------------------------------------------------------------

export async function generateAudio(
  blueprint: ProjectBlueprint,
  aiRouter?: AIRouter,
  aiProvider?: 'auto' | 'gemini' | 'claude' | 'gpt' | 'deepseek'
): Promise<AudioAgentOutput> {
  let config = buildAudioConfig(blueprint)

  if (aiRouter) {
    const systemPrompt = `You are the VibeStudio AI Audio Agent.
Determine the audio configuration based on the ProjectBlueprint.
Return a raw JSON object with this EXACT structure (No Markdown):
{
  "style": "chiptune" | "ambient" | "orchestral" | "synthwave",
  "tempo": number (BPM),
  "key": number (root frequency in Hz),
  "scale": [number, number, ...] (semitone intervals),
  "hasMusic": boolean,
  "hasSfx": boolean,
  "hasAmbient": boolean
}
Ensure it strictly conforms to this schema.`;

    try {
      const response = await aiRouter.generate(`${systemPrompt}\n\nProjectBlueprint: ${JSON.stringify(blueprint)}`, { jsonMode: true, model: aiProvider });
      const rawData = JSON.parse(response.content);
      if (rawData.style && rawData.scale) {
        config = rawData as AudioConfig;
      }
    } catch (e) {
      console.warn('AI Audio config generation failed. Falling back to deterministic config.', e);
    }
  }

  const audioCode = generateAudioCode(config)
  return { config, audioCode }
}
