/**
 * Build System — Game Project Assembler
 * Implements SRS FR-8, FR-9
 *
 * Takes agent outputs (mechanics files, asset registry, audio module)
 * and assembles a runnable Vite project, runs pnpm build, pnpm dev.
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { join } from 'path'
import type { MechanicsOutput } from '../../agents/mechanics/src/mechanics.js'
import type { ProjectBlueprint } from '../../agents/director/src/schema.js'

export interface AssemblyOptions {
  outputDir: string              // absolute path for generated project
  blueprint: ProjectBlueprint
  mechanics: MechanicsOutput
  assetsCode?: string            // generated assets.js content
  audioCode?: string             // generated audio.js content
}

// ---------------------------------------------------------------------------
// Assemble the Vite project (FR-8)
// ---------------------------------------------------------------------------

export function assembleProject(opts: AssemblyOptions): void {
  const { outputDir, blueprint, mechanics, assetsCode, audioCode } = opts

  // 1. Create directory tree
  ensureDir(outputDir)
  ensureDir(join(outputDir, 'src', 'game', 'scenes'))
  ensureDir(join(outputDir, 'src', 'game', 'entities'))
  ensureDir(join(outputDir, 'public'))

  // 2. Write package.json
  const pkg = buildPackageJson(blueprint, mechanics.dependencies)
  writeJson(join(outputDir, 'package.json'), pkg)

  // 3. Write vite.config.js
  write(join(outputDir, 'vite.config.js'), buildViteConfig())

  // 4. Write index.html
  write(join(outputDir, 'index.html'), buildIndexHtml(blueprint))

  // 5. Write src/main.js
  write(join(outputDir, 'src', 'main.js'), buildMainJs())

  // 6. Write generated game files (mechanics agent output)
  for (const file of mechanics.files) {
    const dest = join(outputDir, 'src', 'game', file.path)
    ensureDir(dest.substring(0, dest.lastIndexOf('\\')))
    write(dest, file.content)
  }

  // 7. Write assets module (Asset Agent output or placeholder)
  write(
    join(outputDir, 'src', 'game', 'assets.js'),
    assetsCode ?? buildAssetsPlaceholder()
  )

  // 8. Write audio module (Audio Agent output or placeholder)
  write(
    join(outputDir, 'src', 'game', 'audio.js'),
    audioCode ?? buildAudioPlaceholder()
  )
}

// ---------------------------------------------------------------------------
// File content generators
// ---------------------------------------------------------------------------

function buildPackageJson(
  bp: ProjectBlueprint,
  extraDeps: Record<string, string>
): Record<string, unknown> {
  return {
    name: bp.title.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    private: true,
    description: `Generated by VibeStudio AI — ${bp.title}`,
    scripts: {
      dev:   'vite',
      build: 'vite build',
      preview: 'vite preview',
    },
    dependencies: {
      ...extraDeps,
    },
    devDependencies: {
      vite: '^5.3.1',
    },
  }
}

function buildViteConfig(): string {
  return `import { defineConfig } from 'vite'

export default defineConfig({
  server: { port: 8080, open: true },
  build: {
    outDir: 'dist',
    assetsDir: 'assets',
    rollupOptions: {
      output: { manualChunks: { phaser: ['phaser'] } }
    }
  }
})
`
}

function buildIndexHtml(bp: ProjectBlueprint): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${bp.title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #0a0a12; display: flex; align-items: center; justify-content: center; height: 100vh; overflow: hidden; }
    #game-container canvas { display: block; }
  </style>
</head>
<body>
  <div id="game-container"></div>
  <script type="module" src="/src/main.js"></script>
</body>
</html>
`
}

function buildMainJs(): string {
  return `import 'phaser'
import './game/game.js'
`
}

function buildAssetsPlaceholder(): string {
  return `// Asset Registry — generated by Asset Agent (Phase 2)
// Placeholder: textures are generated procedurally in PreloadScene
export const ASSETS = {}
`
}

function buildAudioPlaceholder(): string {
  return `// Audio Module — generated by Audio Agent (Phase 3)
// Placeholder: audio will use Web Audio API procedurally
export function initAudio() {
  console.log('[AudioAgent] Placeholder — audio generation coming in Phase 3')
}
`
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function ensureDir(dir: string): void {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
}

function write(path: string, content: string): void {
  writeFileSync(path, content, 'utf-8')
}

function writeJson(path: string, data: unknown): void {
  write(path, JSON.stringify(data, null, 2))
}
